language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer self-update
    - composer install

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls