language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer self-update
    - composer install
    - mysql -e 'create database mydb;'
    - php vendor/robmorgan/phinx/bin/phinx migrate
    - php vendor/robmorgan/phinx/bin/phinx -c vendor/idealistsoft/framework-auth/phinx.yml migrate

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls